ALTER TABLE "EdgeConfig"
  ADD COLUMN IF NOT EXISTS "mlEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "mlUrl" TEXT NOT NULL DEFAULT 'http://localhost:8083',
  ADD COLUMN IF NOT EXISTS "mlTimeout" INTEGER NOT NULL DEFAULT 10000,
  ADD COLUMN IF NOT EXISTS "mlProvider" TEXT NOT NULL DEFAULT 'auto',
  ADD COLUMN IF NOT EXISTS "mlWebSearch" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "mlOllamaModel" TEXT NOT NULL DEFAULT 'llama3.3:70b',
  ADD COLUMN IF NOT EXISTS "mlOllamaEmbeddingModel" TEXT NOT NULL DEFAULT 'nomic-embed-text',
  ADD COLUMN IF NOT EXISTS "mlOllamaTimeout" INTEGER NOT NULL DEFAULT 120000,
  ADD COLUMN IF NOT EXISTS "mlGroqModel" TEXT NOT NULL DEFAULT 'llama-3.3-70b-versatile',
  ADD COLUMN IF NOT EXISTS "mlGeminiModel" TEXT NOT NULL DEFAULT 'gemini-2.0-flash-exp',
  ADD COLUMN IF NOT EXISTS "mlGeminiEmbeddingModel" TEXT NOT NULL DEFAULT 'models/text-embedding-004',
  ADD COLUMN IF NOT EXISTS "mlCacheTtl" INTEGER NOT NULL DEFAULT 86400,
  ADD COLUMN IF NOT EXISTS "mlMaxContentLength" INTEGER NOT NULL DEFAULT 10000;
