import type { RoleCapabilityDefinition, RoleCapabilitySection } from './types';

export const CAPABILITY_SECTIONS: RoleCapabilitySection[] = [
  {
    id: 'overview',
    label: 'Overview',
    description: 'Dashboard visibility and top-level operational context.',
  },
  {
    id: 'content',
    label: 'Content',
    description: 'Projects, updates, comments, community, and tag operations.',
  },
  {
    id: 'wallet',
    label: 'Wallet',
    description: 'Wallet health, users, KYC/withdrawals, and risk controls.',
  },
  {
    id: 'engagement',
    label: 'Engagement',
    description: 'Mining configuration, metrics, and referral administration.',
  },
  {
    id: 'access',
    label: 'Access',
    description:
      'User lifecycle management, role management, and applications.',
  },
  {
    id: 'system',
    label: 'System',
    description: 'Audit visibility, notifications, and global settings.',
  },
];

export const ROLE_CAPABILITIES: RoleCapabilityDefinition[] = [
  {
    key: 'overview.dashboard.view',
    label: 'View Dashboard',
    description: 'Access dashboard statistics, activity, and health summaries.',
    section: 'overview',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'content.projects.moderate',
    label: 'Moderate Projects',
    description: 'Review and change project status for moderation workflows.',
    section: 'content',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'content.projects.pause',
    label: 'Pause Projects',
    description:
      'Set project status to paused (reserved for owner/dev/admin authority).',
    section: 'content',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'content.updates.moderate',
    label: 'Moderate Updates',
    description: 'Review and update visibility status of project updates.',
    section: 'content',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'content.comments.moderate',
    label: 'Moderate Comments',
    description: 'Review and moderate update comments across the platform.',
    section: 'content',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'content.community.moderate',
    label: 'Moderate Community',
    description: 'Review and moderate community posts and community comments.',
    section: 'content',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'content.tags.manage',
    label: 'Manage Tags',
    description: 'Create and update primary/secondary taxonomy tags.',
    section: 'content',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'wallet.health.view',
    label: 'View Wallet Health',
    description: 'See wallet provider and settlement health indicators.',
    section: 'wallet',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'wallet.users.view',
    label: 'View Wallet Users',
    description: 'Browse wallet users, balances, and account risk context.',
    section: 'wallet',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'wallet.tips.transactions.view',
    label: 'View Tip Transactions',
    description: 'Read tipping history across mined BNP and token phases.',
    section: 'wallet',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'wallet.tips.settings.mutate',
    label: 'Mutate Tip Settings',
    description: 'Update tipping fee policy and active tipping currency.',
    section: 'wallet',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'wallet.withdrawals.review',
    label: 'Review Withdrawals',
    description: 'Approve or reject withdrawal requests.',
    section: 'wallet',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'wallet.kyc.review',
    label: 'Review KYC',
    description: 'Approve or reject wallet KYC submissions.',
    section: 'wallet',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'wallet.settings.mutate',
    label: 'Mutate Wallet Settings',
    description: 'Edit wallet risk limits, fee configs, and asset pricing.',
    section: 'wallet',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'engagement.mining.view',
    label: 'View Mining Config/Metrics',
    description: 'Read mining configuration and mining metrics.',
    section: 'engagement',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'engagement.mining.mutate',
    label: 'Mutate Mining Config',
    description: 'Update mining coefficients and related operational settings.',
    section: 'engagement',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'engagement.referrals.bind',
    label: 'Bind Referrals',
    description: 'Run admin referral bind overrides.',
    section: 'engagement',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'access.users.view',
    label: 'View Users',
    description: 'Search users and inspect profile/account status.',
    section: 'access',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'access.users.edit_profile',
    label: 'Edit User Profiles',
    description: 'Edit profile fields for managed users.',
    section: 'access',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'access.users.deactivate',
    label: 'Deactivate Users',
    description: 'Deactivate user accounts and revoke sessions.',
    section: 'access',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'access.users.reactivate',
    label: 'Reactivate Users',
    description: 'Reactivate deactivated user accounts.',
    section: 'access',
    roles: ['owner'],
  },
  {
    key: 'access.users.hard_delete',
    label: 'Hard Delete Users',
    description: 'Permanently remove user accounts and linked records.',
    section: 'access',
    roles: ['owner'],
  },
  {
    key: 'access.roles.admin.manage',
    label: 'Manage Admin Role',
    description: 'Grant or revoke admin role assignments.',
    section: 'access',
    roles: ['owner', 'dev'],
  },
  {
    key: 'access.roles.dev.manage',
    label: 'Manage Dev Role',
    description: 'Grant or revoke dev role assignments.',
    section: 'access',
    roles: ['owner'],
  },
  {
    key: 'access.roles.owner.manage',
    label: 'Manage Owner Role',
    description: 'Grant or revoke owner role assignments.',
    section: 'access',
    roles: ['owner'],
  },
  {
    key: 'access.roles.community_admin.manage',
    label: 'Manage Community Admin Role',
    description: 'Grant or revoke community admin role assignments.',
    section: 'access',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'access.roles.community_moderator.manage',
    label: 'Manage Community Moderator Role',
    description: 'Grant or revoke community moderator role assignments.',
    section: 'access',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'access.roles.core_team.manage',
    label: 'Manage Core Team Role',
    description: 'Grant or revoke core team role assignments.',
    section: 'access',
    roles: ['owner'],
  },
  {
    key: 'access.roles.hunter.manage',
    label: 'Manage Hunter Role',
    description: 'Grant or revoke hunter role assignments.',
    section: 'access',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'access.applications.admin.review',
    label: 'Review Admin Applications',
    description: 'Approve or reject admin role applications.',
    section: 'access',
    roles: ['owner'],
  },
  {
    key: 'access.applications.proposal.review',
    label: 'Review Project Proposals',
    description: 'Approve or reject project proposals.',
    section: 'access',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'system.audit_log.view',
    label: 'View Audit Log',
    description: 'Read audit events across admin operations.',
    section: 'system',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'system.ops_events.view',
    label: 'View Ops Events',
    description:
      'Owner/dev operational event stream for email, wallet, tips, and auth workflows.',
    section: 'system',
    roles: ['owner', 'dev'],
  },
  {
    key: 'system.notifications.send',
    label: 'Send Notifications',
    description: 'Broadcast push and in-app notifications.',
    section: 'system',
    roles: ['owner', 'dev', 'admin'],
  },
  {
    key: 'system.social_credentials.manage',
    label: 'Manage Social Credentials',
    description: 'Manage encrypted social media credentials (owner only).',
    section: 'system',
    roles: ['owner'],
  },
  {
    key: 'system.settings.mutate',
    label: 'Mutate Settings',
    description: 'Update global admin console configuration settings.',
    section: 'system',
    roles: ['owner'],
  },
];
